"""Changing id to autoincrement

Revision ID: 6e7b3f094c67
Revises: 5ea600aae299
Create Date: 2023-07-19 23:41:07.492576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7b3f094c67'
down_revision = '5ea600aae299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
