"""fixing total column

Revision ID: 938dc67425ae
Revises: 540639e52803
Create Date: 2023-07-21 03:41:48.597580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938dc67425ae'
down_revision = '540639e52803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'total')
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    op.add_column('items', sa.Column('total', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
