"""Changing items type

Revision ID: 5ea600aae299
Revises: ca979bb23eea
Create Date: 2023-07-19 23:32:31.947603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea600aae299'
down_revision = 'ca979bb23eea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
