"""Add email column to orders table

Revision ID: ca979bb23eea
Revises: 
Create Date: 2023-07-19 23:21:01.081216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca979bb23eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'cep')
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
